### PR TITLE
Added image upload to user recipe submission 

### PR DESCRIPTION
**Pull request by Darkflair**

### CODE REVIEW

**Comment by TomaszTB** [comment]
Nice! Unfortunately I noticed the image disappears after the user adds tags (e.g. user adds image, goes to add tags, finishes adding the tags -> image is gone). Could you make it persist? 
Also, does the image get sent to Firebase to be stored?

**Comment by anf38** [comment]
You can do this with extras. when the intent is triggered and the page changes, you can add information to it so that it will send it back once the user returns to that page

**Comment by Darkflair** [comment]
I got the images working when you view a recipe from the search. However I could not make the image persistent after trying to add tags still looking into that. I tried to use the extras but it does not allow for passing a whole image and my attempts at passing the imageURI didn't work so I will have to revisit that later.

**Comment by TomaszTB** [comment]
What do you mean by being able to view the image from search? Is the recipe image supposed to show up in the green spot next to the recipe title?

**Comment by Darkflair** [comment]
> What do you mean by being able to view the image from search? Is the recipe image supposed to show up in the green spot next to the recipe title?

I am assuming so I did not add the little boxes.

**Comment by TomaszTB** [comment]
Do you mean you got the image to show up in the `ViewRecipe` class? That's cools then. I think we can merge this PR and worry about the image persistence bug in the future

**Comment by Darkflair** [comment]
Yeah it is currently just the viewRecipe class that displays it. The only recipe that will have an image so far is the Grilled Chicken one that is in firebase.

**Comment by anf38** [comment]
i will take a look at it after it is merged. im going to go ahead and accept this merge if thats the only problem

**Pull request merged**
